execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 0..49 run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bGoal: 50 winstreak!"}]}


execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 50 run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bCongratulations for\nhaving a high winstreak!"}]}

execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 51..74 run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bGoal: 75 winstreak!"}]}



execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 75 run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bCongratulations again!\nYou can do it until 100 winstreak!!"}]}

execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 76..94 run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bGoal: 100 winstreak!"}]}


execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 95..99 run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bAlmost there, you can do it!"}]}


execute if score winner_override winner matches -15..0 run execute as @a[x=0,y=65,z=0,tag=!ingame,tag=!afk,tag=!ingame.cos,r=15,m=!c] at @s run execute if score @s winstreak matches 100.. run titleraw @s actionbar {"rawtext":[{"text":"               §b - §r§l§bMinegames §63§r§b - §r"},{"text":"\n§bPoints: "},{"score":{"name":"@s","objective":"winpoints"}},{"text":" | §bDeaths: "},{"score":{"name":"@s","objective":"deaths"}},{"text":" | §bKills: "},{"score":{"name":"@s","objective":"kills"}},{"text":" | §bWin Streak: "},{"score":{"name":"@s","objective":"winstreak"}},{"text":"\n§bCongratulations for having higher winstreak!"}]}
